version: '3'
services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./databases:/fuseki/databases
      - ./config/config.ttl:/fuseki/config.ttl
      - ./config/shiro.ini:/opt/fuseki/shiro.ini
    ports:
      - 3030:3030
